name: Build and deploy gatsby portal

on: 
  pull_request:
    types: [closed]
  push:
    branches: [development]


env: 
  AZURE_WEBAPP_PACKAGE_PATH: '.'      # set this to the path to your web app project, defaults to the repository root
  NODE_VERSION: '16.15.0'                # set this to the node version to use
  NODE_OPTIONS: "--max_old_space_size=5120"

permissions: 
  contents: read

jobs:
  build: 
    runs-on: windows-latest
    steps:
    - name: Checkout gatsby code
      uses: actions/checkout@v3

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '14'
    - name: npm install raaghu-elements
      working-directory: raaghu-elements
      run: |
        npm install
       
    - name: npm install, build, and test raaghu-mfe
      working-directory: ./raaghu-mfe
      run: |
        npm install
        npm run sync-elements    

    - name: npm install gatsby
      working-directory: ./raaghu-mfe/gatsby      
      run: |
        npm install --force

    - name: build gatsby
      working-directory: ./raaghu-mfe/gatsby      
      run: |
        npm run build
    