# This workflow will run tests using node and then publish a package to GitHub Packages when a release is created
# For more information see: https://help.github.com/actions/language-and-framework-guides/publishing-nodejs-packages

name: "Build and publish package to npmjs - Angular"

on:
  release:
    types: [created]
    branches: [main]
  workflow_dispatch:
    
env:
  NODE_VERSION: '16.15.0'                # set this to the node version to use
  NODE_OPTIONS: "--max_old_space_size=5120"

jobs:
  build:
    runs-on: ubuntu-latest
    environment:
      name: 'Package'
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: ${{ env.NODE_VERSION }}
          registry-url: https://npm.pkg.github.com/
          cache: 'npm'
          cache-dependency-path: './raaghu-elements'
      
      - name: Install raaghu-elements
        working-directory: ./raaghu-elements
        run: npm install
      
      - name: Build raaghu-elements
        working-directory: ./raaghu-elements
        run: npm run build-all
      
      - name: Upload artifact for the publish job
        uses: actions/upload-artifact@v3
        with:
          name: node-app
          path: ./raaghu-elements/rds-elements
  
#   publish:
#     runs-on: ubuntu-latest
#     needs: build
#     environment:
#       name: 'Package'
#       url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}
      
#     steps:
#       - name: Download artifact from build job
#         uses: actions/download-artifact@v3
#         with:
#           name: node-app
          
#       - name: Authenticate with private NPM package
#         run: echo "//registry.npmjs.org/:_authToken=${{ secrets.NPM_TOKEN }}" > ~/.npmrc
      
#       - name: Publish rds-elements
#         run: npm publish

        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
          token: ${{ secrets.NPM_TOKEN }}
